name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main
      - releases/*

# Note that when you see patterns like "ref: test-data/v2/basic" within this workflow,
# these refer to "test-data" branches on this actions/checkout repo.
# (For example, test-data/v2/basic -> https://github.com/actions/checkout/tree/test-data/v2/basic)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build
      - run: npm run lint
      - run: npx playwright install
      - run: npm test
